package top.aiprogram.entity;

public class Student extends StudentKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sname
     *
     * @mbggenerated Sat Jul 27 21:29:05 CST 2019
     */
    private String sname;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sex
     *
     * @mbggenerated Sat Jul 27 21:29:05 CST 2019
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.tid
     *
     * @mbggenerated Sat Jul 27 21:29:05 CST 2019
     */
    private Integer tid;

    private Teacher teacher;


    public Student(){}


    public Student(String sname, String sex) {
        this.sname = sname;
        this.sex = sex;
    }
    public Teacher getTeacher() {
        return teacher;
    }

    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sname
     *
     * @return the value of student.sname
     *
     * @mbggenerated Sat Jul 27 21:29:05 CST 2019
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sname
     *
     * @param sname the value for student.sname
     *
     * @mbggenerated Sat Jul 27 21:29:05 CST 2019
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbggenerated Sat Jul 27 21:29:05 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbggenerated Sat Jul 27 21:29:05 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.tid
     *
     * @return the value of student.tid
     *
     * @mbggenerated Sat Jul 27 21:29:05 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.tid
     *
     * @param tid the value for student.tid
     *
     * @mbggenerated Sat Jul 27 21:29:05 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}