package top.aiprogram.entity;

public class StudentKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sid
     *
     * @mbggenerated Sat Jul 27 21:29:05 CST 2019
     */
    private Integer sid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sid
     *
     * @return the value of student.sid
     *
     * @mbggenerated Sat Jul 27 21:29:05 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sid
     *
     * @param sid the value for student.sid
     *
     * @mbggenerated Sat Jul 27 21:29:05 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }
}