package top.aiprogram.entity;

public class TeacherKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tid
     *
     * @mbggenerated Sat Jul 27 21:29:05 CST 2019
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tid
     *
     * @return the value of teacher.tid
     *
     * @mbggenerated Sat Jul 27 21:29:05 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tid
     *
     * @param tid the value for teacher.tid
     *
     * @mbggenerated Sat Jul 27 21:29:05 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}